### PR TITLE
Merging Crypto-metrics-Webapp to main

### PR DESCRIPTION
**Pull request by shegy28**
### Merging a fully functional Crypto-metrics-Webapp to the main branch.
`Crypto Metrics WebApp is a web application and a platform that utilizes the Coincap API to fetch data on different cryptocurrencies and displays the information for each coin in a comprehensive manner.`

**In this branch, I implemented the following:**

- Created a repository and set up react and redux
- Added all needed dependencies
- Made use of Gif-flow and Dev branch as default
- Fetched data from [CoinCap](https://api.coincap.io/v2/assets) API
- Display data from the API
- Ran test for the app using jest testing library
- Added stylings to match the given design
- Updated the readme file to include all requirements

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @shegy28, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- App is working fine👏
- Linter is green (the last commit have a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏

## Required Changes ♻️

- [ ]  Your video is clear and contains an objective description of the project. I would advise you to highlight or show a piece of the code you find interesting or proud of making. It is a project requirement. 
- [ ]  I noticed that you deployed the project on render.com, I would advise you to deploy the application using Heroku or Netlifly, or GitHub pages instead, because these are the platforms Microverse recommends to the students
- [ ] Work on the test again because it did not pass
- 
Capture

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by shegy28** [comment]
well @OLIPLICHE  microverse has advised us to use render.com now so that's why it was use

**Comment by OLIPLICHE** [comment]
> well @OLIPLICHE microverse has advised us to use render.com now so that's why it was use

Okay, move ahead. @shegy28

**Review by frank1738 — APPROVED** [review]
Hi @shegy28 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ All tests are passing 👍 



## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
